---
- import_tasks: preinstall.yaml
- import_tasks: loadbalancer.yaml
- import_tasks: init_kubernetes.yaml
- import_tasks: network.yaml
- import_tasks: join_worker_to_master.yaml
- import_tasks: join_master_to_master.yaml